services:
  app:
    build: .
    volumes:
      - ./data:/data
    restart: on-failure:5
    environment:
      # VPM packages will be served via HTTP instead of file:// URLs
      VPM_BASE_URL: "http://localhost:8080"
